### ISSUE TITLE
Add helper method similar to management command

### ISSUE THREAD

**Issue by philipplaeubli** [dreipol/django-easy-eddie#2]
* django-easy-eddie version: lastest / master
* Django version: 1.11.5
* Python version: 3.4
* Operating System: macOS

### Description
As I want to fetch all unfetched logs once an hour with celery, it would be great to have a helper function i can put into my task directly. 

### What I Did
At the moment you have to use almost the same code from the management command by copy/pasting it into the celery taskL

```
sms_events = SMSEvent.objects.filter(fetched_cloud_watch_log__isnull=True)
fetch_log_events(sms_events=sms_events, log_group_names=CLOUD_WATCH_LOG_GROUP_NAMES)
```
Nice would be if there is either something like this:
```
from easy_eddie.helpers import fetch_latest_log_events
fetch_latest_log_events()
```
or 
```
fetch_log_events(sms_events=SMSEvent.objects.unfetched(), log_group_names=CLOUD_WATCH_LOG_GROUP_NAMES)
```
In that case, I would prefer to have the log_group_names be defaulted to the params defined in the settings:
```
fetch_log_events(sms_events=SMSEvent.objects.unfetched())
```
What do you think?

**Comment by chschuermann** [comment]
@philipplaeubli: I just added a helper function `fetch_logs_of_unprocessed_sms_events()` in 1c78a5113e1828561ed5ae015fc521fec077e77c. What do you think?

**Comment by philipplaeubli** [comment]
Very nice, thank you!
